import "./globals.css";
import NavBar from "../components/NavBar";
import "bootstrap/dist/css/bootstrap.min.css";

export const metadata = {
  title: "Hikma",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
